"""baseline

Revision ID: 0dd629888bfd
Revises:
Create Date: 2026-07-28 13:10:10.109378

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0dd629888bfd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
